### PR TITLE
fix bug with multiple negation patterns

### PR DESCRIPTION
**Pull request by kilianc**
@doowb I tried what you suggest and it resulted in an infinite loop, I added a test suite and it passes but I am in a rush so don't merge it yet

### CODE REVIEW

**Comment by hassanbazzi** [comment]
10/10

**Comment by doowb** [comment]
@kilianc thanks for the PR! I'll take a closer look at the changes later today.

The failing tests for node < 6.0 are due to a dependency. You don't need to worry about those right now, but if you'd like to include the change in this PR, it would be changing `arr-unique` to `array-unique`.

**Comment by kilianc** [comment]
@doowb @jonschlinkert after reviewing the code and the test suite I found a lot of edge cases, bugs and inconsistencies between what's advertised and current behavior. This PR IMHO introduces a consistent behavior with today documentation and `micromatch` api.

Major breaking change: *In order to use negate patterns you need to first include everything `'*'`*

We could do `patterns.every((pattern) => pattern.startsWith('!')) && patterns.unshift('*')` but I would like to hear what you guys think.

Please don't merge either way yet, I would like to squash first.

P.S. the major bug was inverted arguments order in the splice call `splice(i, 1)` vs `splice(1, i)` but splicing the patterns array felt very bad, introducing mutation, but even worse in a for loop.

Thanks!

**Comment by kilianc** [comment]
@doowb @jonschlinkert I really need this to work and I don't wont to fork, rewrite this module and fragmentate the npm ecosystem even more. Let me know if there is a plan to merge this.

**Comment by jonschlinkert** [comment]
> I really need this to work and I don't wont to fork, rewrite this module and fragmentate the npm ecosystem even more. Let me know if there is a plan to merge this.

Given the extensiveness of the changes you made, the PR is more time consuming to review. In the future, you can get your pull request merged faster by only making changes that are necessary for what's mentioned in your issue/pr.

> Please don't merge either way yet, I would like to squash first.

I'm assuming you decided not to squash first?

> after reviewing the code and the test suite I found a lot of edge cases, bugs and inconsistencies between what's advertised and current behavior.

It would be great if you could list them, or any of them. 

> Major breaking change: In order to use negate patterns you need to first include everything '*'

Were the breaking changes 100% necessary for your bugfix?

> but splicing the patterns array felt very bad, introducing mutation, even worse in a for loop

`.splice` is completely fine. A simple `.slice` would have been the easiest thing to do to prevent mutation.

**Comment by kilianc** [comment]
I didn't squash because I was waiting for feedback. As I mentioned earlier in this thread, the library had many edge cases that are inconsistent with the current documentation and expected behavior.

I can open a pull request with a bunch of failing tests to show what I mean.

This PR makes the old test suite pass and addresses the edge cases.

> .splice is completely fine. A simple .slice would have been the easiest thing to do to prevent mutation.

Splicing an Array you are cycling through is usually bad practice and and even after the fix, it still had edge cases.

As I asked earlier "Let me know if there is a plan to merge this." no pressure on time, but if there is not plan to merge it, I will simply publish a new module with the behavior that fits my use case!

**Comment by kilianc** [comment]
@jonschlinkert btw, I just looked at the changes again, and the PR is still pretty small in my opinion, I removed a lot of unnecessary code and put in a new implementation and the test suite still pass.

Honestly I think we spent more time writing these comments than fixing the bug.

**Comment by jonschlinkert** [comment]
Go ahead and publish a new module.

**Pull request closed without merging**
